"""init

Revision ID: d73aad34000f
Revises: 
Create Date: 2021-02-06 12:04:07.112004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73aad34000f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('vegan', sa.Boolean(), nullable=True),
    sa.Column('halal', sa.Boolean(), nullable=True),
    sa.Column('low_carbon', sa.Boolean(), nullable=True),
    sa.Column('high_carbon', sa.Boolean(), nullable=True),
    sa.Column('peanuts', sa.Boolean(), nullable=True),
    sa.Column('tree_nuts', sa.Boolean(), nullable=True),
    sa.Column('wheat', sa.Boolean(), nullable=True),
    sa.Column('gluten', sa.Boolean(), nullable=True),
    sa.Column('soy', sa.Boolean(), nullable=True),
    sa.Column('dairy', sa.Boolean(), nullable=True),
    sa.Column('eggs', sa.Boolean(), nullable=True),
    sa.Column('crustacean_shellfish', sa.Boolean(), nullable=True),
    sa.Column('fish', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addons',
    sa.Column('parent_item_id', sa.Integer(), nullable=True),
    sa.Column('child_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['item.id'], )
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition',
    sa.Column('serving_size', sa.String(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('fat_calories', sa.Integer(), nullable=True),
    sa.Column('total_fat', sa.String(), nullable=True),
    sa.Column('saturated_fat', sa.String(), nullable=True),
    sa.Column('trans_fat', sa.String(), nullable=True),
    sa.Column('cholesterol', sa.String(), nullable=True),
    sa.Column('sodium', sa.String(), nullable=True),
    sa.Column('total_carbohydrate', sa.String(), nullable=True),
    sa.Column('dietary_fiber', sa.String(), nullable=True),
    sa.Column('total_sugars', sa.String(), nullable=True),
    sa.Column('protein', sa.String(), nullable=True),
    sa.Column('total_fat_pdv', sa.Integer(), nullable=True),
    sa.Column('saturated_fat_pdv', sa.Integer(), nullable=True),
    sa.Column('cholesterol_pdv', sa.Integer(), nullable=True),
    sa.Column('sodium_pdv', sa.Integer(), nullable=True),
    sa.Column('total_carbohydrate_pdv', sa.Integer(), nullable=True),
    sa.Column('dietary_fiber_pdv', sa.Integer(), nullable=True),
    sa.Column('vitamin_a_pdv', sa.Integer(), nullable=True),
    sa.Column('vitamin_c_pdv', sa.Integer(), nullable=True),
    sa.Column('calcium_pdv', sa.Integer(), nullable=True),
    sa.Column('iron_pdv', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('meals_x_items',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals_x_items')
    op.drop_table('nutrition')
    op.drop_table('meal')
    op.drop_table('addons')
    op.drop_table('location')
    op.drop_table('item')
    # ### end Alembic commands ###
